version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
      - '33060:33060'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_MYSQL}
      MYSQL_USER: ${USER_MYSQL}
      MYSQL_PASSWORD: ${PASSWORD_MYSQL}
      MYSQL_DATABASE: ${DATABASE_MYSQL}

  adminer:
    image: adminer
    ports:
      - 80:8080
